networks:
  traefik:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    entrypoint: /etc/traefik/entrypoint.sh
    networks:
      - traefik
    ports:
      - "${TRFK_HTTP_PORT}:80"
      - "${TRFK_HTTPS_PORT}:443"
    volumes:
      - ./config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env

#  whoami:
#    container_name: whoami
#    image: traefik/whoami
#    restart: unless-stopped
#    networks:
#      - traefik
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
#      - "traefik.http.services.whoami.loadbalancer.server.port=80"
