http:
  routers:
    api:
      entryPoints: ['websecure']
      rule: "Host(`dashboard.{{ env "TRFK_ACME_DOMAIN" }}`)"
      service: api@internal

    whoami:
      entryPoints: ['websecure']
      rule: "Host(`whoami.{{ env "TRFK_ACME_DOMAIN" }}`)"
      service: whoami

  services:
    whoami:
      loadBalancer:
        servers:
          - url: "http://whoami"
