[http.routers.traefik]
  rule = "Host(`traefik.localhost`)"
  service = "api@internal"

# [http.routers.whoami]
#   rule = "Host(`whoami.localhost`)"
#   service = "whoami"

# [http.services]
#   [http.services.whoami.loadBalancer]
#     [[http.services.whoami.loadBalancer.servers]]
#       url = "http://whoami"
