[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[api]
  dashboard = true
  insecure = true

[pilot]
  dashboard = false

[entryPoints]
  [entryPoints.web]
    address = ":$TRFK_HTTP_PORT"
  [entryPoints.websecure]
    address = ":$TRFK_HTTPS_PORT"

[providers.docker]
  exposedByDefault = false
  network = "traefik"

[providers.file]
  filename = "/etc/traefik/dynamic.toml"
  watch = true
