[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[api]
  dashboard = true

[pilot]
  dashboard = false

[providers.docker]
  exposedByDefault = false
  network = "traefik"

[providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true

[entryPoints]
  [entryPoints.web]
    address = ":$TRFK_HTTP_PORT"
  [entryPoints.websecure]
    address = ":$TRFK_HTTPS_PORT"
    [entryPoints.websecure.http.tls]
      certResolver = "myresolver"
      [[entryPoints.websecure.http.tls.domains]]
        main = "$TRFK_ACME_DOMAIN"
        sans = ["*.$TRFK_ACME_DOMAIN"]

[certificatesResolvers.myresolver.acme]
  email = "$TRFK_ACME_EMAIL"
  storage = "acme.json"
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "$TRFK_ACME_PROVIDER"
    resolvers = ["$TRFK_ACME_RESOLVER"]
